### ISSUE TITLE
Feature: Spell Correct for user inputs

### ISSUE THREAD

**Issue by pro-panda** [sugarlabs/countries-activity#5]
**Problem Statement**
It is possible that the user might be typing the correct country but the input given might be off by one character(maybe two). In that case, the user gets the message:
`Sorry, <wrong_spelling> is not in my list`

**Proposed Feature:**
 - If the answer is off by 1 character (maybe 2, if the length of the answer crosses a threshold (say, 7)), then a message of this form can be displayed in any 1 of these options:
 1. `Did you mean <correct_spelling> ? (y/n)`
   - if `n` is entered, then it is marked as a wrong answer
   - if 'y' is entered, then it is marked as a correct answer
 2. `The correct spelling is: <correct_spelling>`
   - The answer is considered correct automatically

If agreed to be implemented, I would like to work on this

**Comment by nswarup14** [comment]
Closed via #9

**Comment by nswarup14** [comment]
@pro-panda 
We should close this issue.

**Comment by quozl** [comment]
GitHub automation doesn't know what **Implements** means in your opening comment of https://github.com/sugarlabs/countries-activity/pull/9.

Use **Fixes** instead.

**Comment by pro-panda** [comment]
Fixed in 1214586
